### ISSUE TITLE
Kirby regular chaining

### ISSUE THREAD

**Issue by Mark-Pilkington** [johannschopplich/kirby-vue3-starterkit#16]
Hi there, pardon my question, but is it possible to use the Kirby "regular" chaining system like in the PHP starterkit after importing `useSite`?

For instance: in a _component_ (not a view, I mean), is it possible to reference content from another page?

```
<button class="button" />
   {{ site.children.find('somepage').title }}
</button>
```

The "regular" chaining system would be like:
`site()->children()->find('somepage')->title()`

For now, it says
`Unhandled Promise Rejection: TypeError: Array.prototype.find callback must be a function
`

Thx! 😃

**Comment by johannschopplich** [comment]
You're talking about the Kirby API, used by the Panel for example. You can read more about it [in the docs](https://getkirby.com/docs/guide/api/introduction#endpoints).

It's not base of this starterkit. It requires a custom read-only user to be setup, authentication and more, which I wouldn't prefer for a Vue integration. 

Of course you can access other page's data. Take a look into: https://github.com/johannschopplich/kirby-vue3-starterkit/blob/83b986e458ae535744b89b280bd14a41918c119d/frontend/src/views/Home.vue

You can pass the desired page to the `usePage` hook and use the content anywhere, even in components.

For example:

```vue
<template>
  <button v-if="somepage.isReady">
    somepage.title
  </button>
</template>

<script>
import { usePage } from '../hooks'

export default {
  setup () {
    const somepage = usePage('somepage')

    // Example of `isReadyPromise()` page method
    ;(async () => {
      await photography.isReadyPromise()
      // Do something with the reactive page object
      console.log('Somepage page data has been loaded.')
      console.log(somepage.title)
    })()

    return {
      somepage
    }
  }
}
</script>
```

Since each page's data is fetched lazily, I've created the `isReady` key and `isReadyPromise` function for in-template use as well as inside the setup method.

**Comment by Mark-Pilkington** [comment]
Ah ok, I guess I would need to set up the page I want to pull the data from inside `setup` and then use it like `somepage.title`?

Like:

```
setup () {
    const page = usePage()
    const somepage = usePage('somepage')

    ;(async () => {
      await somepage.isReadyPromise()
    })()

    return {
      page,
      somepage
    }
  }
```

**Comment by Mark-Pilkington** [comment]
Ah, you already answered before I posted mine 😃

**Comment by johannschopplich** [comment]
Exactly. Keep in mind that the `isReadyPromise()` method is optional. You'd only need it if you want to use the page's data inside the setup method. For the template use the `isReady` key (without the suffix "promise").

**Comment by Mark-Pilkington** [comment]
Ah, ok, cool! nice

**Comment by johannschopplich** [comment]
Example for usage of data inside the setup method:

```js
const somepage = usePage('somepage')

// Example of `isReadyPromise()` page method
;(async () => {
  // Data isn't available
  console.log(somepage.title) // null

  await somepage.isReadyPromise()
  console.log('Somepage page data has been loaded.')

  // Now you can access it
  console.log(somepage.title)
})()
```
