### ISSUE TITLE
Storing and accessing development/production variables in env

### ISSUE THREAD

**Issue by MichaelPrecel** [johannschopplich/kirby-vue3-starterkit#44]
Hi @johannschopplich ! Thanks as always for an amazing framework.

Sorry if this is a n00b question, but I'm working with API Keys where I have one (unrestricted) key for dev and one restricted to the final domain for production. When the website runs a build I'd like it to use the production one and the unrestricted one during dev. 

With Vite I can use import.meta.VITE_API_KEY in my front end component to get the value, however this always takes the value from the .env file, even after running a build and if I have a .env.production file with a different string as the same env value. Removing .env and using two.env.development / .env.production file crashes the dev process.

What am I missing here?

Thanks as always.

**Comment by johannschopplich** [comment]
Hi Michael, 

glad to hear you're enjoying this starter kit. Unfortunately, I can't help you. Since Vite is used, every option including the [env variables and modes](https://vitejs.dev/guide/env-and-mode.html#env-variables-and-modes) are inferred. Please head over to the docs and try again… It should work just like the documentation says.

Make sure you're using the latest Vite version and good luck!
