### ISSUE TITLE
Router transitions

### ISSUE THREAD

**Issue by getflourish** [johannschopplich/kirby-vue3-starterkit#8]
After a first quick test, router transitions only seem to work from child pages to parent pages. 

When using transition `mode="out-in"`, navigation breaks as the new page gets appended to the bottom of the current page.

What I tried in `App.vue`:

```
<transition :name="'fade'" mode="in-out">
    <router-view :key="route.path" />
</transition>
```

```
.fade-enter-active, .fade-leave-active {
  transition: opacity .5s;
}
.fade-enter, .fade-leave-to /* .fade-leave-active below version 2.1.8 */ {
  opacity: 0;
}
```

**Comment by johannschopplich** [comment]
Transition setup has changed in Vue Router 4. See the [next docs](https://next.router.vuejs.org/guide/advanced/transitions.html), specifically since [transition must now be used inside of `RouterView` via the `v-slot` API](https://next.router.vuejs.org/guide/migration/#router-view-keep-alive-and-transition).

You also have to wait for the router for the initial transition inside `main.js`: `await router.isReady()`.

A good source for is the [transition playground inside the router repo itself](https://github.com/vuejs/vue-router-next/tree/master/e2e/transitions).

Closing the issue because it's not a question related to this repository.

**Comment by getflourish** [comment]
Okay, need to finally get into Vue 3 to make use of this awesome repo :)

**Comment by johannschopplich** [comment]
The migration guides provide a good overview of the changes. Glad to hear you want to use this setup! 🙂
